### ISSUE TITLE
Installation does not work on 10.10.1 (14B25)

### ISSUE THREAD

**Issue by banzo** [remko/be-non-apple#2]
I am following the steps here https://github.com/remko/be-non-apple/#installation

The new layout does not appear in the Settings > Keyboard > Input sources list

I tried opening the .keylayout file in ukulele but it complains about malformed xml tags.

**Comment by remko** [comment]
Hi banzo,
Are you saving the raw version of the file? You can get it here: 

https://raw.githubusercontent.com/remko/be-non-apple/master/Belgian%20(Non-Apple).keylayout
https://raw.githubusercontent.com/remko/be-non-apple/master/Belgian%20(IBM).keylayout

**Comment by banzo** [comment]
Thanks for your answer, that was indeed the problem!
